[phases.setup]
nixPkgs = [
  "php84",
  "php84Extensions.intl",
  "php84Extensions.zip",
  "php84Extensions.gd",
  "php84Extensions.bcmath"
]

[phases.build]
cmds = [
  "echo 'skip node build for now'"
]
